#配置Mybatis规则
mybatis:
  mapper-locations:
    classpath: com/xiaoxin/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  config-location: 可以不写全局配置文件，所有配置文件的配置都放在configuration配置项中即可
#配置数据池druid
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmanager
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

